### ISSUE TITLE
Make compilation failed

### ISSUE THREAD

**Issue by harrysy088** [ambertime/amberchain#7]
Make compilation failed.  I am using ubuntu 18.04

The error is:
  CXX      wallet/libbitcoin_wallet_a-crypter.o
wallet/crypter.cpp: In member function ‘bool CCrypter::Encrypt(const CKeyingMaterial&, std::vector<unsigned char>&)’:
wallet/crypter.cpp:62:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
wallet/crypter.cpp: In member function ‘bool CCrypter::Decrypt(const std::vector<unsigned char>&, CKeyingMaterial&)’:
wallet/crypter.cpp:89:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
Makefile:3394: recipe for target 'wallet/libbitcoin_wallet_a-crypter.o' failed

**Comment by harrysy088** [comment]
I was able to complete the compilation using ubuntu 16.04

However the following steps seems to be wrong:

Connect to the AmberChain testnet

*To connect to the currently deployed amber-testnet chain, run any of the following:

./amberchaind amber-testnet@13.250.176.149:7362
./amberchaind amber-testnet@13.124.35.92:7362
./amberchaind amber-testnet@47.75.251.94:7362
Run the Chain CLI

# amberchain/src >
./amberchain-cli <chain name>
# ie: ./amberchain-cli amber-testchain
You can run the help command in the CLI to see a list of APIs
help shows a detailed description of th API and parameters
# amber-testchain >
help
help listaddresses

**Comment by harrysy088** [comment]
I was able to compile using ubuntu 16.04

Does this mean using ubuntu 18.04 will not work? If so, please specify which OS is this compatible to

**Comment by harrysy088** [comment]
How do I get the from-address and csr for the requestauthority?

**Comment by maroon-olivia** [comment]
Hi,

We have added the steps in generating the CSR, and retrieving the from-address for requestauthority API in the documentation. Please use this as reference: https://github.com/ambertime/amberchain/blob/amber-dev/docs/AmberTime%20Blockchain%20Documentation_v1.2.pdf

**Comment by harrysy088** [comment]
Thanks. You can now closed this issue.

I have send a requestauthority.
